### PR TITLE
Added Algo2

### PR DESCRIPTION
**Pull request by mattkemp**
details are in the commit notes, added another algorithm for assigning players. This has been tested and refined over two leagues so far and has had good results. Algorithm 2 is an option in settings, if not enabled then program operates as normal.

### CODE REVIEW

**Comment by smashery** [comment]
Looks great - I'm keen to include this. I was never really happy with my algorithm. 
One thing, though: I haven't used the ClickOnce feature before - but it seems that since it's been enabled in this branch, the solution doesn't compile without first selecting/generating one's own private key (or disabling ClickOnce), since the pfx is rightly not included in the repo. I'm not aware of what best-practice is in this regard - is there a way of using this feature that is more portable for a public repo?

**Comment by mattkemp** [comment]
Actually I didn't mean to change anything like that, I just tried a "publish" thinking it might make a better exe than the debug one, but the installer it made just seemed to be more complicated. I'll go back in to the code and see if I can take it out. I thought having the exe was valuable for people who just want to grab the working program though, do you agree?

**Comment by smashery** [comment]
Yeah I definitely agree.

**Comment by mattkemp** [comment]
sorry about the messy commits! The only change needed was to the csproj. Should be sorted now.

**Pull request merged**
